//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ConsumableStorage {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblC_StoID;
		protected global::System.Web.UI.WebControls.TextBox txtC_Barcode;
		protected global::System.Web.UI.WebControls.TextBox txtCount;
		protected global::System.Web.UI.WebControls.TextBox txtUserName;
		protected global::System.Web.UI.WebControls.TextBox txtDatetime;
		protected global::System.Web.UI.WebControls.TextBox txtRemarks;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
