//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblMultiFiber {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtID;
		protected global::System.Web.UI.WebControls.TextBox txtScan_ID;
		protected global::System.Web.UI.WebControls.TextBox txtScanTime;
		protected global::System.Web.UI.WebControls.TextBox txtUser_ID;
		protected global::System.Web.UI.WebControls.TextBox txtProductID;
		protected global::System.Web.UI.WebControls.TextBox txtConnectorID;
		protected global::System.Web.UI.WebControls.TextBox txtLightMode;
		protected global::System.Web.UI.WebControls.TextBox txtDataSource;
		protected global::System.Web.UI.WebControls.TextBox txtMicroscope;
		protected global::System.Web.UI.WebControls.TextBox txtDataFilePath;
		protected global::System.Web.UI.WebControls.TextBox txtFiberCount;
		protected global::System.Web.UI.WebControls.TextBox txtFiberPitch;
		protected global::System.Web.UI.WebControls.TextBox txtFibersPerRow;
		protected global::System.Web.UI.WebControls.TextBox txtFiberRowPitch;
		protected global::System.Web.UI.WebControls.TextBox txtRowsVerticalOffset;
		protected global::System.Web.UI.WebControls.TextBox txtFiberCaptureShape;
		protected global::System.Web.UI.WebControls.TextBox txtShape;
		protected global::System.Web.UI.WebControls.TextBox txtFiberDiameter;
		protected global::System.Web.UI.WebControls.TextBox txtFerruleType;
		protected global::System.Web.UI.WebControls.TextBox txtFerruleCount;
		protected global::System.Web.UI.WebControls.TextBox txtGuideStructureType;
		protected global::System.Web.UI.WebControls.TextBox txtGuideStructurePitch;
		protected global::System.Web.UI.WebControls.TextBox txtNominalYAngle;
		protected global::System.Web.UI.WebControls.TextBox txtConnectorType;
		protected global::System.Web.UI.WebControls.TextBox txtScanSegmentsNmb;
		protected global::System.Web.UI.WebControls.TextBox txtROI_width;
		protected global::System.Web.UI.WebControls.TextBox txtROI_height;
		protected global::System.Web.UI.WebControls.TextBox txtAvgDiameter;
		protected global::System.Web.UI.WebControls.TextBox txtExtractingDiameter;
		protected global::System.Web.UI.WebControls.TextBox txtMinModulation;
		protected global::System.Web.UI.WebControls.TextBox txtTopPixRemove;
		protected global::System.Web.UI.WebControls.TextBox txtTopPixLeft;
		protected global::System.Web.UI.WebControls.TextBox txtSampleType;
		protected global::System.Web.UI.WebControls.TextBox txtMultimode;
		protected global::System.Web.UI.WebControls.TextBox txtMeasurementConfig;
		protected global::System.Web.UI.WebControls.TextBox txtPassFail;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffH;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffH_min;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffH_max;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffH_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffAdjH;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffAdjH_min;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffAdjH_max;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFibDiffAdjH_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtMaxCoreDip;
		protected global::System.Web.UI.WebControls.TextBox txtMaxCoreDip_min;
		protected global::System.Web.UI.WebControls.TextBox txtMaxCoreDip_max;
		protected global::System.Web.UI.WebControls.TextBox txtMaxCoreDip_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtROC_X;
		protected global::System.Web.UI.WebControls.TextBox txtROC_X_min;
		protected global::System.Web.UI.WebControls.TextBox txtROC_X_max;
		protected global::System.Web.UI.WebControls.TextBox txtROC_X_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtROC_Y;
		protected global::System.Web.UI.WebControls.TextBox txtROC_Y_min;
		protected global::System.Web.UI.WebControls.TextBox txtROC_Y_max;
		protected global::System.Web.UI.WebControls.TextBox txtROC_Y_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtXEndFaceAngle;
		protected global::System.Web.UI.WebControls.TextBox txtXEndFaceAngle_min;
		protected global::System.Web.UI.WebControls.TextBox txtXEndFaceAngle_max;
		protected global::System.Web.UI.WebControls.TextBox txtXEndFaceAngle_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtYEndFaceAngle;
		protected global::System.Web.UI.WebControls.TextBox txtYEndFaceAngle_min;
		protected global::System.Web.UI.WebControls.TextBox txtYEndFaceAngle_max;
		protected global::System.Web.UI.WebControls.TextBox txtYEndFaceAngle_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtFlatnessDeviation;
		protected global::System.Web.UI.WebControls.TextBox txtFlatnessDeviation_min;
		protected global::System.Web.UI.WebControls.TextBox txtFlatnessDeviation_max;
		protected global::System.Web.UI.WebControls.TextBox txtFlatnessDeviation_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtFiberProtrusion_min;
		protected global::System.Web.UI.WebControls.TextBox txtFiberProtrusion_max;
		protected global::System.Web.UI.WebControls.TextBox txtFiberProtrusion_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtFiberROC_min;
		protected global::System.Web.UI.WebControls.TextBox txtFiberROC_max;
		protected global::System.Web.UI.WebControls.TextBox txtFiberROC_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtFiberHeight;
		protected global::System.Web.UI.WebControls.TextBox txtFiberCoreDip;
		protected global::System.Web.UI.WebControls.TextBox txtFiberROC;
		protected global::System.Web.UI.WebControls.TextBox txtTestPassed;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayXAng;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayXAng_min;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayXAng_max;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayXAng_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayYAng;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayYAng_min;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayYAng_max;
		protected global::System.Web.UI.WebControls.TextBox txtFibArrayYAng_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtCoplanarity;
		protected global::System.Web.UI.WebControls.TextBox txtCoplanarity_min;
		protected global::System.Web.UI.WebControls.TextBox txtCoplanarity_max;
		protected global::System.Web.UI.WebControls.TextBox txtCoplanarity_Pass;
		protected global::System.Web.UI.WebControls.TextBox txtMinusCoplanarity;
		protected global::System.Web.UI.WebControls.TextBox txtMinusCoplanarity_min;
		protected global::System.Web.UI.WebControls.TextBox txtMinusCoplanarity_max;
		protected global::System.Web.UI.WebControls.TextBox txtMinusCoplanarity_Pass;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
