//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tblMultiFiber {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblScan_ID;
	protected global::System.Web.UI.WebControls.Label lblScanTime;
	protected global::System.Web.UI.WebControls.Label lblUser_ID;
	protected global::System.Web.UI.WebControls.Label lblProductID;
	protected global::System.Web.UI.WebControls.Label lblConnectorID;
	protected global::System.Web.UI.WebControls.Label lblLightMode;
	protected global::System.Web.UI.WebControls.Label lblDataSource;
	protected global::System.Web.UI.WebControls.Label lblMicroscope;
	protected global::System.Web.UI.WebControls.Label lblDataFilePath;
	protected global::System.Web.UI.WebControls.Label lblFiberCount;
	protected global::System.Web.UI.WebControls.Label lblFiberPitch;
	protected global::System.Web.UI.WebControls.Label lblFibersPerRow;
	protected global::System.Web.UI.WebControls.Label lblFiberRowPitch;
	protected global::System.Web.UI.WebControls.Label lblRowsVerticalOffset;
	protected global::System.Web.UI.WebControls.Label lblFiberCaptureShape;
	protected global::System.Web.UI.WebControls.Label lblShape;
	protected global::System.Web.UI.WebControls.Label lblFiberDiameter;
	protected global::System.Web.UI.WebControls.Label lblFerruleType;
	protected global::System.Web.UI.WebControls.Label lblFerruleCount;
	protected global::System.Web.UI.WebControls.Label lblGuideStructureType;
	protected global::System.Web.UI.WebControls.Label lblGuideStructurePitch;
	protected global::System.Web.UI.WebControls.Label lblNominalYAngle;
	protected global::System.Web.UI.WebControls.Label lblConnectorType;
	protected global::System.Web.UI.WebControls.Label lblScanSegmentsNmb;
	protected global::System.Web.UI.WebControls.Label lblROI_width;
	protected global::System.Web.UI.WebControls.Label lblROI_height;
	protected global::System.Web.UI.WebControls.Label lblAvgDiameter;
	protected global::System.Web.UI.WebControls.Label lblExtractingDiameter;
	protected global::System.Web.UI.WebControls.Label lblMinModulation;
	protected global::System.Web.UI.WebControls.Label lblTopPixRemove;
	protected global::System.Web.UI.WebControls.Label lblTopPixLeft;
	protected global::System.Web.UI.WebControls.Label lblSampleType;
	protected global::System.Web.UI.WebControls.Label lblMultimode;
	protected global::System.Web.UI.WebControls.Label lblMeasurementConfig;
	protected global::System.Web.UI.WebControls.Label lblPassFail;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffH;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffH_min;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffH_max;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffH_Pass;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffAdjH;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffAdjH_min;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffAdjH_max;
	protected global::System.Web.UI.WebControls.Label lblMaxFibDiffAdjH_Pass;
	protected global::System.Web.UI.WebControls.Label lblMaxCoreDip;
	protected global::System.Web.UI.WebControls.Label lblMaxCoreDip_min;
	protected global::System.Web.UI.WebControls.Label lblMaxCoreDip_max;
	protected global::System.Web.UI.WebControls.Label lblMaxCoreDip_Pass;
	protected global::System.Web.UI.WebControls.Label lblROC_X;
	protected global::System.Web.UI.WebControls.Label lblROC_X_min;
	protected global::System.Web.UI.WebControls.Label lblROC_X_max;
	protected global::System.Web.UI.WebControls.Label lblROC_X_Pass;
	protected global::System.Web.UI.WebControls.Label lblROC_Y;
	protected global::System.Web.UI.WebControls.Label lblROC_Y_min;
	protected global::System.Web.UI.WebControls.Label lblROC_Y_max;
	protected global::System.Web.UI.WebControls.Label lblROC_Y_Pass;
	protected global::System.Web.UI.WebControls.Label lblXEndFaceAngle;
	protected global::System.Web.UI.WebControls.Label lblXEndFaceAngle_min;
	protected global::System.Web.UI.WebControls.Label lblXEndFaceAngle_max;
	protected global::System.Web.UI.WebControls.Label lblXEndFaceAngle_Pass;
	protected global::System.Web.UI.WebControls.Label lblYEndFaceAngle;
	protected global::System.Web.UI.WebControls.Label lblYEndFaceAngle_min;
	protected global::System.Web.UI.WebControls.Label lblYEndFaceAngle_max;
	protected global::System.Web.UI.WebControls.Label lblYEndFaceAngle_Pass;
	protected global::System.Web.UI.WebControls.Label lblFlatnessDeviation;
	protected global::System.Web.UI.WebControls.Label lblFlatnessDeviation_min;
	protected global::System.Web.UI.WebControls.Label lblFlatnessDeviation_max;
	protected global::System.Web.UI.WebControls.Label lblFlatnessDeviation_Pass;
	protected global::System.Web.UI.WebControls.Label lblFiberProtrusion_min;
	protected global::System.Web.UI.WebControls.Label lblFiberProtrusion_max;
	protected global::System.Web.UI.WebControls.Label lblFiberProtrusion_Pass;
	protected global::System.Web.UI.WebControls.Label lblFiberROC_min;
	protected global::System.Web.UI.WebControls.Label lblFiberROC_max;
	protected global::System.Web.UI.WebControls.Label lblFiberROC_Pass;
	protected global::System.Web.UI.WebControls.Label lblFiberHeight;
	protected global::System.Web.UI.WebControls.Label lblFiberCoreDip;
	protected global::System.Web.UI.WebControls.Label lblFiberROC;
	protected global::System.Web.UI.WebControls.Label lblTestPassed;
	protected global::System.Web.UI.WebControls.Label lblFibArrayXAng;
	protected global::System.Web.UI.WebControls.Label lblFibArrayXAng_min;
	protected global::System.Web.UI.WebControls.Label lblFibArrayXAng_max;
	protected global::System.Web.UI.WebControls.Label lblFibArrayXAng_Pass;
	protected global::System.Web.UI.WebControls.Label lblFibArrayYAng;
	protected global::System.Web.UI.WebControls.Label lblFibArrayYAng_min;
	protected global::System.Web.UI.WebControls.Label lblFibArrayYAng_max;
	protected global::System.Web.UI.WebControls.Label lblFibArrayYAng_Pass;
	protected global::System.Web.UI.WebControls.Label lblCoplanarity;
	protected global::System.Web.UI.WebControls.Label lblCoplanarity_min;
	protected global::System.Web.UI.WebControls.Label lblCoplanarity_max;
	protected global::System.Web.UI.WebControls.Label lblCoplanarity_Pass;
	protected global::System.Web.UI.WebControls.Label lblMinusCoplanarity;
	protected global::System.Web.UI.WebControls.Label lblMinusCoplanarity_min;
	protected global::System.Web.UI.WebControls.Label lblMinusCoplanarity_max;
	protected global::System.Web.UI.WebControls.Label lblMinusCoplanarity_Pass;


       
    }
}
