//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.FixtureList {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtBarCode;
		protected global::System.Web.UI.WebControls.TextBox txtFixture_Name;
		protected global::System.Web.UI.WebControls.TextBox txtInstallLocation;
		protected global::System.Web.UI.WebControls.TextBox txtF_State;
		protected global::System.Web.UI.WebControls.TextBox txtLogDate;
		protected global::System.Web.UI.WebControls.TextBox txtLogUser;
		protected global::System.Web.UI.WebControls.TextBox txtCareUser;
		protected global::System.Web.UI.WebControls.TextBox txtUseDate;
		protected global::System.Web.UI.WebControls.TextBox txtScrapDate;
		protected global::System.Web.UI.WebControls.TextBox txtFAY_ID;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
