//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.FixtureList {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblBarCode;
	protected global::System.Web.UI.WebControls.Label lblFixture_Name;
	protected global::System.Web.UI.WebControls.Label lblInstallLocation;
	protected global::System.Web.UI.WebControls.Label lblF_State;
	protected global::System.Web.UI.WebControls.Label lblLogDate;
	protected global::System.Web.UI.WebControls.Label lblLogUser;
	protected global::System.Web.UI.WebControls.Label lblCareUser;
	protected global::System.Web.UI.WebControls.Label lblUseDate;
	protected global::System.Web.UI.WebControls.Label lblScrapDate;
	protected global::System.Web.UI.WebControls.Label lblFAY_ID;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
