;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014-2-22 16:03:08

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1002	1002	; 1.2 *   Welcome to AO_MCP_System Welcome MCP\Aboot.txt
#define IDH_1001	1001	; 登陆中心.htm 信息中心\登陆中心.htm
