;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014-2-22 16:03:08

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1002=Welcome MCP\Aboot.txt	; 1.2 *   Welcome to AO_MCP_System
IDH_1001=信息中心\登陆中心.htm	; 登陆中心.htm
