//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Material_Receive {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtReceiveID;
		protected global::System.Web.UI.WebControls.TextBox txtMaterialNum;
		protected global::System.Web.UI.WebControls.TextBox txtClientNum;
		protected global::System.Web.UI.WebControls.TextBox txtCount;
		protected global::System.Web.UI.WebControls.TextBox txtUserID;
		protected global::System.Web.UI.WebControls.TextBox txtWorkStationID;
		protected global::System.Web.UI.WebControls.TextBox txtDataTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
