//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Rework {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtSN;
		protected global::System.Web.UI.WebControls.TextBox txtPigtailType;
		protected global::System.Web.UI.WebControls.TextBox txtCount;
		protected global::System.Web.UI.WebControls.TextBox txtRejectID;
		protected global::System.Web.UI.WebControls.TextBox txtRejectDescribe;
		protected global::System.Web.UI.WebControls.TextBox txtDisposeID;
		protected global::System.Web.UI.WebControls.TextBox txtDisposeDescribe;
		protected global::System.Web.UI.WebControls.TextBox txtLength;
		protected global::System.Web.UI.WebControls.TextBox txtResult;
		protected global::System.Web.UI.WebControls.TextBox txtReworkID;
		protected global::System.Web.UI.WebControls.TextBox txtVerifyID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
