//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Rework {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblSN;
	protected global::System.Web.UI.WebControls.Label lblPigtailType;
	protected global::System.Web.UI.WebControls.Label lblCount;
	protected global::System.Web.UI.WebControls.Label lblRejectID;
	protected global::System.Web.UI.WebControls.Label lblRejectDescribe;
	protected global::System.Web.UI.WebControls.Label lblDisposeID;
	protected global::System.Web.UI.WebControls.Label lblDisposeDescribe;
	protected global::System.Web.UI.WebControls.Label lblLength;
	protected global::System.Web.UI.WebControls.Label lblResult;
	protected global::System.Web.UI.WebControls.Label lblReworkID;
	protected global::System.Web.UI.WebControls.Label lblVerifyID;


       
    }
}
