//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tb_PrintRecord {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblSN;
		protected global::System.Web.UI.WebControls.TextBox txtStaff;
		protected global::System.Web.UI.WebControls.TextBox txtDataTime;
		protected global::System.Web.UI.WebControls.TextBox txtLabellMode;
		protected global::System.Web.UI.WebControls.TextBox txtBatchNo;
		protected global::System.Web.UI.WebControls.TextBox txtOrderID;
	protected global::System.Web.UI.WebControls.Label lblID_Key;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
