//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Equipment_Maintain {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblMat_ID;
		protected global::System.Web.UI.WebControls.TextBox txtFormNum;
		protected global::System.Web.UI.WebControls.TextBox txtAss_Num;
		protected global::System.Web.UI.WebControls.TextBox txtAss_Name;
		protected global::System.Web.UI.WebControls.TextBox txtAss_MakeNum;
		protected global::System.Web.UI.WebControls.TextBox txtAss_Type;
		protected global::System.Web.UI.WebControls.TextBox txtApply_Date;
		protected global::System.Web.UI.WebControls.TextBox txtApply_Describe;
		protected global::System.Web.UI.WebControls.TextBox txtApply_User;
		protected global::System.Web.UI.WebControls.TextBox txtMaintain_Cause;
		protected global::System.Web.UI.WebControls.TextBox txtMaintain_Describe;
		protected global::System.Web.UI.WebControls.TextBox txtmaintain_User;
		protected global::System.Web.UI.WebControls.TextBox txtMaintain_Date;
		protected global::System.Web.UI.WebControls.TextBox txtCheck_Deseribe;
		protected global::System.Web.UI.WebControls.TextBox txtCheck_Result;
		protected global::System.Web.UI.WebControls.TextBox txtCheck_Date;
		protected global::System.Web.UI.WebControls.TextBox txtCheck_User;
		protected global::System.Web.UI.WebControls.TextBox txtRemarks;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
