//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Equipment_Maintain {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblMat_ID;
	protected global::System.Web.UI.WebControls.Label lblFormNum;
	protected global::System.Web.UI.WebControls.Label lblAss_Num;
	protected global::System.Web.UI.WebControls.Label lblAss_Name;
	protected global::System.Web.UI.WebControls.Label lblAss_MakeNum;
	protected global::System.Web.UI.WebControls.Label lblAss_Type;
	protected global::System.Web.UI.WebControls.Label lblApply_Date;
	protected global::System.Web.UI.WebControls.Label lblApply_Describe;
	protected global::System.Web.UI.WebControls.Label lblApply_User;
	protected global::System.Web.UI.WebControls.Label lblMaintain_Cause;
	protected global::System.Web.UI.WebControls.Label lblMaintain_Describe;
	protected global::System.Web.UI.WebControls.Label lblmaintain_User;
	protected global::System.Web.UI.WebControls.Label lblMaintain_Date;
	protected global::System.Web.UI.WebControls.Label lblCheck_Deseribe;
	protected global::System.Web.UI.WebControls.Label lblCheck_Result;
	protected global::System.Web.UI.WebControls.Label lblCheck_Date;
	protected global::System.Web.UI.WebControls.Label lblCheck_User;
	protected global::System.Web.UI.WebControls.Label lblRemarks;


       
    }
}
