//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Lapping_Receive {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblLp_ID;
	protected global::System.Web.UI.WebControls.Label lblCount;
	protected global::System.Web.UI.WebControls.Label lblReceiveUserID;
	protected global::System.Web.UI.WebControls.Label lblSendUserID;
	protected global::System.Web.UI.WebControls.Label lblLappingReceiveID;
	protected global::System.Web.UI.WebControls.Label lblDataTime;


       
    }
}
